name: Code Review with AI
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: .
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_API_MODEL: "deepseek/deepseek-chat-v3-0324"
          OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1"
          exclude: "yarn.lock,dist/**,*.md,package-lock.json"
          PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.number }}
